-- V1__create_structure.sql
-- Estructura de base de datos purificada en 3FN para Marweld Backend.
-- Define tablas catálogo para estados de negocio y estandariza constraints.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- =========================================================================
-- TABLAS CATÁLOGO INDEPENDIENTES
-- =========================================================================

CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE_VERIFICACION_CORREO',
    CONSTRAINT uq_roles_nombre_rol UNIQUE (nombre_rol),
    CONSTRAINT chk_roles_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE permisos (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso VARCHAR(120) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_permisos_nombre_permiso UNIQUE (nombre_permiso)
);

CREATE TABLE estados_pedido (
    id_estado_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_estados_pedido_codigo UNIQUE (codigo)
);

CREATE TABLE estados_pago (
    id_estado_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_estados_pago_codigo UNIQUE (codigo)
);

CREATE TABLE metodos_pago (
    id_metodo_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_metodos_pago_codigo UNIQUE (codigo)
);

CREATE TABLE tipos_movimiento (
    id_tipo_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_tipos_movimiento_codigo UNIQUE (codigo)
);

CREATE TABLE tipos_notificacion (
    id_tipo_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_tipos_notificacion_codigo UNIQUE (codigo)
);

CREATE TABLE estados_carrito (
    id_estado_carrito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_estados_carrito_codigo UNIQUE (codigo)
);

CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(120) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT uq_categorias_nombre_categoria UNIQUE (nombre_categoria),
    CONSTRAINT chk_categorias_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE estados_reposicion (
    id_estado_reposicion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_estados_reposicion_codigo UNIQUE (codigo)
);

CREATE TABLE proveedores (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    nombre VARCHAR(180) NOT NULL,
    ruc VARCHAR(11),
    contacto VARCHAR(120),
    telefono VARCHAR(30),
    correo VARCHAR(320),
    direccion TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_proveedores_public_id UNIQUE (public_id),
    CONSTRAINT uq_proveedores_nombre UNIQUE (nombre),
    CONSTRAINT chk_proveedores_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- =========================================================================
-- TABLAS DE ENTIDADES CORE
-- =========================================================================

CREATE TABLE rol_permiso (
    id_rol_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    id_permiso INTEGER NOT NULL,
    CONSTRAINT fk_rol_permiso_roles
        FOREIGN KEY (id_rol) REFERENCES roles (id_rol),
    CONSTRAINT fk_rol_permiso_permisos
        FOREIGN KEY (id_permiso) REFERENCES permisos (id_permiso),
    CONSTRAINT uq_rol_permiso_rol_permiso UNIQUE (id_rol, id_permiso)
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_rol INTEGER NOT NULL,
    nombre VARCHAR(160) NOT NULL,
    correo VARCHAR(320) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuarios_roles
        FOREIGN KEY (id_rol) REFERENCES roles (id_rol),
    CONSTRAINT uq_usuarios_public_id UNIQUE (public_id),
    CONSTRAINT uq_usuarios_correo UNIQUE (correo),
    CONSTRAINT chk_usuarios_estado CHECK (estado IN ('ACTIVO', 'INACTIVO', 'PENDIENTE_VERIFICACION_CORREO'))
);

CREATE TABLE sesiones_usuario (
    id_sesion_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_usuario INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVA',
    ip VARCHAR(45),
    user_agent TEXT,
    fecha_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_ultimo_uso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMP,
    CONSTRAINT fk_sesiones_usuario_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT uq_sesiones_usuario_public_id UNIQUE (public_id),
    CONSTRAINT chk_sesiones_usuario_estado CHECK (estado IN ('ACTIVA', 'CERRADA'))
);

CREATE TABLE refresh_tokens (
    id_refresh_token INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion_usuario INTEGER NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_emision TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP NOT NULL,
    fecha_revocacion TIMESTAMP,
    CONSTRAINT fk_refresh_tokens_sesiones_usuario
        FOREIGN KEY (id_sesion_usuario) REFERENCES sesiones_usuario (id_sesion_usuario),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT chk_refresh_tokens_estado CHECK (estado IN ('ACTIVO', 'REVOCADO', 'EXPIRADO'))
);

CREATE TABLE jwt_revocados (
    id_jwt_revocado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jti VARCHAR(120) NOT NULL,
    id_sesion_usuario INTEGER,
    fecha_expiracion TIMESTAMP NOT NULL,
    fecha_revocacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo TEXT,
    CONSTRAINT fk_jwt_revocados_sesiones_usuario
        FOREIGN KEY (id_sesion_usuario) REFERENCES sesiones_usuario (id_sesion_usuario),
    CONSTRAINT uq_jwt_revocados_jti UNIQUE (jti)
);

CREATE TABLE clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_usuario INTEGER NOT NULL,
    direccion TEXT NOT NULL,
    documento VARCHAR(30) NOT NULL,
    CONSTRAINT fk_clientes_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT uq_clientes_public_id UNIQUE (public_id),
    CONSTRAINT uq_clientes_id_usuario UNIQUE (id_usuario),
    CONSTRAINT uq_clientes_documento UNIQUE (documento)
);

CREATE TABLE trabajadores (
    id_trabajador INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    cargo VARCHAR(120) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trabajadores_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT uq_trabajadores_id_usuario UNIQUE (id_usuario),
    CONSTRAINT chk_trabajadores_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE tipos_producto (
    id_tipo_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(50) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uq_tipos_producto_codigo UNIQUE (codigo)
);

CREATE TABLE productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_categoria INTEGER NOT NULL,
    id_tipo_producto INTEGER NOT NULL,
    nombre VARCHAR(180) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(12, 2) NOT NULL DEFAULT 0,
    unidad_medida VARCHAR(40) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT fk_productos_categorias
        FOREIGN KEY (id_categoria) REFERENCES categorias (id_categoria),
    CONSTRAINT fk_productos_tipos_producto
        FOREIGN KEY (id_tipo_producto) REFERENCES tipos_producto (id_tipo_producto),
    CONSTRAINT uq_productos_public_id UNIQUE (public_id),
    CONSTRAINT chk_productos_precio_non_negative CHECK (precio >= 0),
    CONSTRAINT chk_productos_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE inventarios (
    id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    stock_actual INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 0,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventarios_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT uq_inventarios_id_producto UNIQUE (id_producto),
    CONSTRAINT chk_inventarios_stock_actual_non_negative CHECK (stock_actual >= 0),
    CONSTRAINT chk_inventarios_stock_minimo_non_negative CHECK (stock_minimo >= 0)
);

CREATE TABLE movimientos_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    id_tipo_movimiento INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    motivo TEXT,
    fecha_movimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movimientos_inventario_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT fk_movimientos_inventario_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_movimientos_inventario_tipos_movimiento
        FOREIGN KEY (id_tipo_movimiento) REFERENCES tipos_movimiento (id_tipo_movimiento),
    CONSTRAINT chk_movimientos_inventario_cantidad_positive CHECK (cantidad > 0)
);

CREATE TABLE solicitudes_reposicion (
    id_solicitud_reposicion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_producto INTEGER NOT NULL,
    id_usuario_solicitante INTEGER NOT NULL,
    id_proveedor_sugerido INTEGER,
    id_estado_reposicion INTEGER NOT NULL,
    id_movimiento INTEGER,
    cantidad_solicitada INTEGER NOT NULL,
    cantidad_aprobada INTEGER,
    cantidad_recibida INTEGER,
    stock_actual INTEGER NOT NULL,
    justificacion TEXT NOT NULL,
    motivo_rechazo TEXT,
    notas_administrador TEXT,
    id_usuario_revision INTEGER,
    fecha_revision TIMESTAMP,
    id_usuario_aprobacion INTEGER,
    fecha_aprobacion TIMESTAMP,
    id_usuario_rechazo INTEGER,
    fecha_rechazo TIMESTAMP,
    id_usuario_recepcion INTEGER,
    fecha_recepcion TIMESTAMP,
    fecha_solicitud TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_eliminacion TIMESTAMP,
    CONSTRAINT fk_solicitudes_reposicion_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT fk_solicitudes_reposicion_usuarios_solicitante
        FOREIGN KEY (id_usuario_solicitante) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_solicitudes_reposicion_proveedores
        FOREIGN KEY (id_proveedor_sugerido) REFERENCES proveedores (id_proveedor),
    CONSTRAINT fk_solicitudes_reposicion_estados
        FOREIGN KEY (id_estado_reposicion) REFERENCES estados_reposicion (id_estado_reposicion),
    CONSTRAINT fk_solicitudes_reposicion_movimientos
        FOREIGN KEY (id_movimiento) REFERENCES movimientos_inventario (id_movimiento),
    CONSTRAINT fk_solicitudes_reposicion_usuarios_revision
        FOREIGN KEY (id_usuario_revision) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_solicitudes_reposicion_usuarios_aprobacion
        FOREIGN KEY (id_usuario_aprobacion) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_solicitudes_reposicion_usuarios_rechazo
        FOREIGN KEY (id_usuario_rechazo) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_solicitudes_reposicion_usuarios_recepcion
        FOREIGN KEY (id_usuario_recepcion) REFERENCES usuarios (id_usuario),
    CONSTRAINT uq_solicitudes_reposicion_public_id UNIQUE (public_id),
    CONSTRAINT chk_solicitudes_reposicion_cantidad_solicitada CHECK (cantidad_solicitada > 0),
    CONSTRAINT chk_solicitudes_reposicion_cantidad_aprobada CHECK (cantidad_aprobada IS NULL OR cantidad_aprobada >= 0),
    CONSTRAINT chk_solicitudes_reposicion_cantidad_recibida CHECK (cantidad_recibida IS NULL OR cantidad_recibida >= 0),
    CONSTRAINT chk_solicitudes_reposicion_stock_actual CHECK (stock_actual >= 0)
);

CREATE TABLE carritos (
    id_carrito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_cliente INTEGER,
    token_visitante VARCHAR(80),
    id_estado_carrito INTEGER NOT NULL,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carritos_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_carritos_estados_carrito
        FOREIGN KEY (id_estado_carrito) REFERENCES estados_carrito (id_estado_carrito),
    CONSTRAINT uq_carritos_public_id UNIQUE (public_id),
    CONSTRAINT chk_carritos_total_non_negative CHECK (total >= 0),
    CONSTRAINT chk_carritos_owner_exclusivo CHECK (
        (id_cliente IS NOT NULL AND token_visitante IS NULL)
        OR (id_cliente IS NULL AND token_visitante IS NOT NULL)
    )
);

CREATE TABLE detalle_carrito (
    id_detalle_carrito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_detalle_carrito_carritos
        FOREIGN KEY (id_carrito) REFERENCES carritos (id_carrito),
    CONSTRAINT fk_detalle_carrito_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    -- Evitar duplicidad de producto en un mismo carrito
    CONSTRAINT uq_detalle_carrito_carrito_producto UNIQUE (id_carrito, id_producto),
    CONSTRAINT chk_detalle_carrito_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_carrito_precio_unitario_non_negative CHECK (precio_unitario >= 0),
    CONSTRAINT chk_detalle_carrito_subtotal_non_negative CHECK (subtotal >= 0)
);

CREATE TABLE pedidos (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_cliente INTEGER NOT NULL,
    id_carrito INTEGER NOT NULL,
    id_estado_pedido INTEGER NOT NULL,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedidos_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_pedidos_carritos
        FOREIGN KEY (id_carrito) REFERENCES carritos (id_carrito),
    CONSTRAINT fk_pedidos_estados_pedido
        FOREIGN KEY (id_estado_pedido) REFERENCES estados_pedido (id_estado_pedido),
    CONSTRAINT uq_pedidos_public_id UNIQUE (public_id),
    CONSTRAINT chk_pedidos_total_non_negative CHECK (total >= 0)
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_detalle_pedido_pedidos
        FOREIGN KEY (id_pedido) REFERENCES pedidos (id_pedido),
    CONSTRAINT fk_detalle_pedido_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    -- Evitar duplicidad de producto en un mismo pedido
    CONSTRAINT uq_detalle_pedido_pedido_producto UNIQUE (id_pedido, id_producto),
    CONSTRAINT chk_detalle_pedido_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_pedido_precio_unitario_non_negative CHECK (precio_unitario >= 0),
    CONSTRAINT chk_detalle_pedido_subtotal_non_negative CHECK (subtotal >= 0)
);

CREATE TABLE ventas_pos (
    id_venta_pos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_trabajador INTEGER NOT NULL,
    id_cliente INTEGER,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    id_metodo_pago INTEGER NOT NULL,
    fecha_venta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ventas_pos_trabajadores
        FOREIGN KEY (id_trabajador) REFERENCES trabajadores (id_trabajador),
    CONSTRAINT fk_ventas_pos_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_ventas_pos_metodos_pago
        FOREIGN KEY (id_metodo_pago) REFERENCES metodos_pago (id_metodo_pago),
    CONSTRAINT uq_ventas_pos_public_id UNIQUE (public_id),
    CONSTRAINT chk_ventas_pos_total_non_negative CHECK (total >= 0)
);

CREATE TABLE detalle_venta_pos (
    id_detalle_venta_pos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta_pos INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_detalle_venta_pos_ventas_pos
        FOREIGN KEY (id_venta_pos) REFERENCES ventas_pos (id_venta_pos),
    CONSTRAINT fk_detalle_venta_pos_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    -- Evitar duplicidad de producto en una misma venta POS
    CONSTRAINT uq_detalle_venta_pos_venta_producto UNIQUE (id_venta_pos, id_producto),
    CONSTRAINT chk_detalle_venta_pos_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_venta_pos_precio_unitario_non_negative CHECK (precio_unitario >= 0),
    CONSTRAINT chk_detalle_venta_pos_subtotal_non_negative CHECK (subtotal >= 0)
);

CREATE TABLE pagos (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_pedido INTEGER,
    id_venta_pos INTEGER,
    id_metodo_pago INTEGER NOT NULL,
    monto NUMERIC(12, 2) NOT NULL DEFAULT 0,
    id_estado_pago INTEGER NOT NULL,
    fecha_pago TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pagos_pedidos
        FOREIGN KEY (id_pedido) REFERENCES pedidos (id_pedido),
    CONSTRAINT fk_pagos_ventas_pos
        FOREIGN KEY (id_venta_pos) REFERENCES ventas_pos (id_venta_pos),
    CONSTRAINT fk_pagos_metodos_pago
        FOREIGN KEY (id_metodo_pago) REFERENCES metodos_pago (id_metodo_pago),
    CONSTRAINT fk_pagos_estados_pago
        FOREIGN KEY (id_estado_pago) REFERENCES estados_pago (id_estado_pago),
    CONSTRAINT uq_pagos_public_id UNIQUE (public_id),
    CONSTRAINT chk_pagos_monto_non_negative CHECK (monto >= 0),
    CONSTRAINT chk_pagos_origen_exclusivo CHECK (
        (id_pedido IS NOT NULL AND id_venta_pos IS NULL)
        OR (id_pedido IS NULL AND id_venta_pos IS NOT NULL)
    )
);

CREATE TABLE eventos_sistema (
    id_evento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tipo_evento VARCHAR(120) NOT NULL,
    entidad_tipo VARCHAR(80),
    entidad_id INTEGER,
    payload JSONB,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_evento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_procesado TIMESTAMP,
    CONSTRAINT uq_eventos_sistema_public_id UNIQUE (public_id),
    CONSTRAINT chk_eventos_sistema_estado CHECK (estado IN ('PENDIENTE', 'PROCESADO', 'ERROR'))
);

CREATE TABLE notificaciones (
    id_notificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_evento INTEGER,
    id_usuario INTEGER NOT NULL,
    id_tipo_notificacion INTEGER NOT NULL,
    titulo VARCHAR(180) NOT NULL,
    contenido TEXT NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_lectura TIMESTAMP,
    CONSTRAINT fk_notificaciones_eventos_sistema
        FOREIGN KEY (id_evento) REFERENCES eventos_sistema (id_evento),
    CONSTRAINT fk_notificaciones_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_notificaciones_tipos_notificacion
        FOREIGN KEY (id_tipo_notificacion) REFERENCES tipos_notificacion (id_tipo_notificacion),
    CONSTRAINT uq_notificaciones_public_id UNIQUE (public_id),
    CONSTRAINT chk_notificaciones_estado CHECK (estado IN ('PENDIENTE', 'LEIDA'))
);

CREATE TABLE entregas_notificacion (
    id_entrega INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_notificacion INTEGER NOT NULL,
    canal VARCHAR(30) NOT NULL,
    destinatario VARCHAR(320) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    external_id VARCHAR(255),
    error TEXT,
    fecha_programada TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_envio TIMESTAMP,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_entregas_notificacion_notificaciones
        FOREIGN KEY (id_notificacion) REFERENCES notificaciones (id_notificacion),
    CONSTRAINT chk_entregas_notificacion_canal CHECK (canal IN ('EMAIL', 'APP')),
    CONSTRAINT chk_entregas_notificacion_estado CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'ERROR'))
);

CREATE TABLE sesiones_chatbot (
    id_sesion_chatbot INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    tipo_actor VARCHAR(30) NOT NULL,
    id_cliente INTEGER,
    id_trabajador INTEGER,
    token_visitante VARCHAR(80),
    id_carrito INTEGER,
    estado VARCHAR(30) NOT NULL DEFAULT 'ABIERTA',
    fecha_inicio TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_cierre TIMESTAMP,
    CONSTRAINT fk_sesiones_chatbot_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_sesiones_chatbot_trabajadores
        FOREIGN KEY (id_trabajador) REFERENCES trabajadores (id_trabajador),
    CONSTRAINT fk_sesiones_chatbot_carritos
        FOREIGN KEY (id_carrito) REFERENCES carritos (id_carrito),
    CONSTRAINT uq_sesiones_chatbot_public_id UNIQUE (public_id),
    CONSTRAINT chk_sesiones_chatbot_estado CHECK (estado IN ('ABIERTA', 'CERRADA')),
    CONSTRAINT chk_sesiones_chatbot_tipo_actor CHECK (tipo_actor IN ('CLIENTE', 'TRABAJADOR', 'VISITANTE')),
    CONSTRAINT chk_sesiones_chatbot_actor_exclusivo CHECK (
        (id_cliente IS NOT NULL AND id_trabajador IS NULL AND token_visitante IS NULL)
        OR (id_cliente IS NULL AND id_trabajador IS NOT NULL AND token_visitante IS NULL)
        OR (id_cliente IS NULL AND id_trabajador IS NULL AND token_visitante IS NOT NULL)
    )
);

CREATE TABLE mensajes_chatbot (
    id_mensaje_chatbot INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_sesion_chatbot INTEGER NOT NULL,
    emisor VARCHAR(30) NOT NULL,
    contenido TEXT NOT NULL,
    fecha_mensaje TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mensajes_chatbot_sesiones_chatbot
        FOREIGN KEY (id_sesion_chatbot) REFERENCES sesiones_chatbot (id_sesion_chatbot),
    CONSTRAINT uq_mensajes_chatbot_public_id UNIQUE (public_id),
    CONSTRAINT chk_mensajes_chatbot_emisor CHECK (emisor IN ('USUARIO', 'BOT', 'SISTEMA'))
);

CREATE TABLE resenas_producto (
    id_resena INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    calificacion INTEGER NOT NULL,
    comentario TEXT,
    aprobada BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_resenas_producto_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_resenas_producto_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT uq_resenas_producto_cliente_producto UNIQUE (id_cliente, id_producto),
    CONSTRAINT chk_resenas_producto_calificacion CHECK (calificacion BETWEEN 1 AND 5)
);

CREATE TABLE faq_chatbot (
    id_faq INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta VARCHAR(255) NOT NULL,
    respuesta TEXT NOT NULL,
    palabras_clave TEXT,
    categoria VARCHAR(80) NOT NULL DEFAULT 'GENERAL',
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT uq_faq_chatbot_pregunta UNIQUE (pregunta),
    CONSTRAINT chk_faq_chatbot_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

CREATE TABLE codigos_verificacion (
    id_codigo_verificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    codigo VARCHAR(6) NOT NULL,
    fecha_expiracion TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT fk_codigos_verificacion_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT chk_codigos_verificacion_estado CHECK (estado IN ('PENDIENTE', 'UTILIZADO', 'EXPIRADO'))
);

CREATE TABLE usuarios_mfa_metodos (
    id_usuario_mfa_metodo INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    metodo VARCHAR(30) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_activacion TIMESTAMP,
    fecha_desactivacion TIMESTAMP,
    CONSTRAINT fk_usuarios_mfa_metodos_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT uq_usuarios_mfa_metodos_usuario_metodo UNIQUE (id_usuario, metodo),
    CONSTRAINT chk_usuarios_mfa_metodos_metodo CHECK (metodo IN ('TOTP', 'EMAIL_OTP')),
    CONSTRAINT chk_usuarios_mfa_metodos_estado CHECK (estado IN ('PENDIENTE', 'ACTIVO', 'INACTIVO'))
);

CREATE TABLE usuarios_mfa_totp (
    id_usuario_mfa_totp INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_mfa_metodo INTEGER NOT NULL,
    secreto_cifrado TEXT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuarios_mfa_totp_metodos
        FOREIGN KEY (id_usuario_mfa_metodo) REFERENCES usuarios_mfa_metodos (id_usuario_mfa_metodo),
    CONSTRAINT uq_usuarios_mfa_totp_metodo UNIQUE (id_usuario_mfa_metodo)
);

CREATE TABLE desafios_mfa (
    id_desafio_mfa INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_usuario INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    intentos_fallidos INTEGER NOT NULL DEFAULT 0,
    max_intentos INTEGER NOT NULL DEFAULT 5,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP NOT NULL,
    fecha_consumo TIMESTAMP,
    CONSTRAINT fk_desafios_mfa_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT uq_desafios_mfa_public_id UNIQUE (public_id),
    CONSTRAINT chk_desafios_mfa_estado CHECK (estado IN ('PENDIENTE', 'CONSUMIDO', 'EXPIRADO', 'BLOQUEADO')),
    CONSTRAINT chk_desafios_mfa_intentos CHECK (intentos_fallidos >= 0 AND max_intentos > 0)
);

CREATE TABLE codigos_mfa_email (
    id_codigo_mfa_email INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_desafio_mfa INTEGER,
    codigo_hash VARCHAR(255) NOT NULL,
    proposito VARCHAR(30) NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    CONSTRAINT fk_codigos_mfa_email_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT fk_codigos_mfa_email_desafios_mfa
        FOREIGN KEY (id_desafio_mfa) REFERENCES desafios_mfa (id_desafio_mfa),
    CONSTRAINT chk_codigos_mfa_email_proposito CHECK (proposito IN ('ENROLLMENT', 'LOGIN')),
    CONSTRAINT chk_codigos_mfa_email_estado CHECK (estado IN ('PENDIENTE', 'UTILIZADO', 'EXPIRADO'))
);

-- =========================================================================
-- AMPLIACIÓN PARA EL MÓDULO DE CHATBOT (ESPECIFICACIONES, COMPATIBILIDAD Y AUDITORÍA)
-- =========================================================================

-- Especificaciones técnicas estructuradas de productos (para modo experto y RAG)
CREATE TABLE especificaciones_producto (
    id_especificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    clave VARCHAR(100) NOT NULL,
    valor TEXT NOT NULL,
    CONSTRAINT fk_especificaciones_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON DELETE CASCADE,
    -- Evitar duplicidad de la misma clave de especificación en un producto
    CONSTRAINT uq_especificaciones_producto_clave UNIQUE (id_producto, clave)
);

-- Relaciones de compatibilidad y venta cruzada
CREATE TABLE relaciones_producto (
    id_relacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto_origen INTEGER NOT NULL, -- Producto asociado (ej. electrodo, boquilla)
    id_producto_destino INTEGER NOT NULL, -- Producto principal (ej. máquina soldadora)
    tipo_relacion VARCHAR(50) NOT NULL,
    CONSTRAINT fk_relaciones_producto_origen
        FOREIGN KEY (id_producto_origen) REFERENCES productos (id_producto) ON DELETE CASCADE,
    CONSTRAINT fk_relaciones_producto_destino
        FOREIGN KEY (id_producto_destino) REFERENCES productos (id_producto) ON DELETE CASCADE,
    CONSTRAINT chk_relaciones_producto_tipo CHECK (tipo_relacion IN (
        'CONSUMIBLE_DE',       -- Insumos consumibles directos (ej. soldadura para máquina)
        'REPUESTO_DE',          -- Partes o repuestos de repuesto (ej. boquilla para antorcha)
        'COMPLEMENTARIO_DE',    -- Accesorios complementarios (ej. máscara para máquina)
        'SUSTITUTO_DE',         -- Producto alternativo / sustituto por falta de stock
        'FRECUENTE_CONJUNTO'    -- Productos que se suelen comprar juntos
    )),
    -- Evita duplicidad de la misma relación dirigida
    CONSTRAINT uq_relaciones_producto_asociacion UNIQUE (id_producto_origen, id_producto_destino, tipo_relacion)
);

-- Documentos de ayuda y conocimiento (RAG extendido)
CREATE TABLE documentos_conocimiento (
    id_documento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    titulo VARCHAR(255) NOT NULL,
    contenido TEXT NOT NULL,
    fuente_url VARCHAR(255),
    categoria VARCHAR(80) NOT NULL DEFAULT 'GENERAL',
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_documentos_conocimiento_public_id UNIQUE (public_id),
    CONSTRAINT chk_documentos_conocimiento_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- Métricas de procesamiento y telemetría de mensajes chatbot (1:1 con mensajes_chatbot)
CREATE TABLE telemetria_mensaje_chatbot (
    id_mensaje_chatbot INTEGER NOT NULL PRIMARY KEY,
    intent_detectado VARCHAR(100),
    confianza_intent NUMERIC(5, 4) CHECK (confianza_intent BETWEEN 0 AND 1),
    modelo_utilizado VARCHAR(100),
    tokens_entrada INTEGER DEFAULT 0,
    tokens_salida INTEGER DEFAULT 0,
    latencia_ms INTEGER DEFAULT 0,
    CONSTRAINT fk_telemetria_mensaje_mensajes
        FOREIGN KEY (id_mensaje_chatbot) REFERENCES mensajes_chatbot (id_mensaje_chatbot) ON DELETE CASCADE
);

-- Productos específicos trazados en la conversación (N:M mensajes-productos)
CREATE TABLE productos_mensaje_chatbot (
    id_mensaje_chatbot INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    rol_producto VARCHAR(50) NOT NULL,
    CONSTRAINT fk_productos_mensaje_mensajes
        FOREIGN KEY (id_mensaje_chatbot) REFERENCES mensajes_chatbot (id_mensaje_chatbot) ON DELETE CASCADE,
    CONSTRAINT fk_productos_mensaje_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto) ON DELETE CASCADE,
    CONSTRAINT chk_productos_mensaje_rol CHECK (rol_producto IN ('MENCIONADO', 'RECOMENDADO', 'SELECCIONADO')),
    PRIMARY KEY (id_mensaje_chatbot, id_producto, rol_producto)
);

-- Registro e historial de auditoría de acciones sobre el carrito desde el chat
CREATE TABLE auditoria_carrito_chatbot (
    id_auditoria_carrito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mensaje_chatbot INTEGER NOT NULL,
    id_carrito INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    tipo_operacion VARCHAR(50) NOT NULL,
    cantidad_anterior INTEGER,
    cantidad_nueva INTEGER NOT NULL,
    fecha_operacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_auditoria_carrito_mensaje
        FOREIGN KEY (id_mensaje_chatbot) REFERENCES mensajes_chatbot (id_mensaje_chatbot),
    CONSTRAINT fk_auditoria_carrito_carrito
        FOREIGN KEY (id_carrito) REFERENCES carritos (id_carrito),
    CONSTRAINT fk_auditoria_carrito_producto
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT chk_auditoria_carrito_tipo CHECK (tipo_operacion IN ('AGREGAR', 'QUITAR', 'MODIFICAR_CANTIDAD'))
);

-- Registro de errores conversacionales y técnicos de IA
CREATE TABLE errores_chatbot (
    id_error INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_mensaje_chatbot INTEGER,
    codigo_error VARCHAR(80) NOT NULL,
    mensaje_error TEXT NOT NULL,
    detalle_tecnico TEXT,
    fecha_error TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_errores_chatbot_mensaje
        FOREIGN KEY (id_mensaje_chatbot) REFERENCES mensajes_chatbot (id_mensaje_chatbot) ON DELETE SET NULL
);
