-- Initial MVP schema generated from docs/diagram_db.md.
-- Internal identifiers remain integer identities; public-facing entities expose public_id UUID.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(80) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT uk_roles_nombre_rol UNIQUE (nombre_rol)
);

CREATE TABLE permisos (
    id_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_permiso VARCHAR(120) NOT NULL,
    descripcion TEXT,
    CONSTRAINT uk_permisos_nombre_permiso UNIQUE (nombre_permiso)
);

CREATE TABLE rol_permiso (
    id_rol_permiso INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    id_permiso INTEGER NOT NULL,
    CONSTRAINT fk_rol_permiso_roles
        FOREIGN KEY (id_rol) REFERENCES roles (id_rol),
    CONSTRAINT fk_rol_permiso_permisos
        FOREIGN KEY (id_permiso) REFERENCES permisos (id_permiso),
    CONSTRAINT uk_rol_permiso_rol_permiso UNIQUE (id_rol, id_permiso)
);

CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_rol INTEGER NOT NULL,
    nombre VARCHAR(160) NOT NULL,
    correo VARCHAR(320) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    telefono VARCHAR(30),
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_registro TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuarios_roles
        FOREIGN KEY (id_rol) REFERENCES roles (id_rol),
    CONSTRAINT uk_usuarios_public_id UNIQUE (public_id),
    CONSTRAINT uk_usuarios_correo UNIQUE (correo)
);

CREATE TABLE clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_usuario INTEGER NOT NULL,
    direccion TEXT NOT NULL,
    documento VARCHAR(30) NOT NULL,
    CONSTRAINT fk_clientes_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT uk_clientes_public_id UNIQUE (public_id),
    CONSTRAINT uk_clientes_id_usuario UNIQUE (id_usuario),
    CONSTRAINT uk_clientes_documento UNIQUE (documento)
);

CREATE TABLE trabajadores (
    id_trabajador INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    cargo VARCHAR(120) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    fecha_ingreso TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_trabajadores_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT uk_trabajadores_id_usuario UNIQUE (id_usuario)
);

CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_categoria VARCHAR(120) NOT NULL,
    descripcion TEXT,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT uk_categorias_nombre_categoria UNIQUE (nombre_categoria)
);

CREATE TABLE productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_categoria INTEGER NOT NULL,
    nombre VARCHAR(180) NOT NULL,
    descripcion TEXT,
    precio NUMERIC(12, 2) NOT NULL DEFAULT 0,
    unidad_medida VARCHAR(40) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ACTIVO',
    CONSTRAINT fk_productos_categorias
        FOREIGN KEY (id_categoria) REFERENCES categorias (id_categoria),
    CONSTRAINT uk_productos_public_id UNIQUE (public_id),
    CONSTRAINT ck_productos_precio_non_negative CHECK (precio >= 0)
);

CREATE TABLE inventarios (
    id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    stock_actual INTEGER NOT NULL DEFAULT 0,
    stock_minimo INTEGER NOT NULL DEFAULT 0,
    fecha_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventarios_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT uk_inventarios_id_producto UNIQUE (id_producto),
    CONSTRAINT ck_inventarios_stock_actual_non_negative CHECK (stock_actual >= 0),
    CONSTRAINT ck_inventarios_stock_minimo_non_negative CHECK (stock_minimo >= 0)
);

CREATE TABLE movimientos_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    tipo_movimiento VARCHAR(40) NOT NULL,
    cantidad INTEGER NOT NULL,
    motivo TEXT,
    fecha_movimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_movimientos_inventario_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT fk_movimientos_inventario_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT ck_movimientos_inventario_cantidad_positive CHECK (cantidad > 0)
);

CREATE TABLE carritos (
    id_carrito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_cliente INTEGER NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'ABIERTO',
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carritos_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT uk_carritos_public_id UNIQUE (public_id),
    CONSTRAINT ck_carritos_total_non_negative CHECK (total >= 0)
);

CREATE TABLE detalle_carrito (
    id_detalle_carrito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_detalle_carrito_carritos
        FOREIGN KEY (id_carrito) REFERENCES carritos (id_carrito),
    CONSTRAINT fk_detalle_carrito_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT ck_detalle_carrito_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_carrito_precio_unitario_non_negative CHECK (precio_unitario >= 0),
    CONSTRAINT ck_detalle_carrito_subtotal_non_negative CHECK (subtotal >= 0)
);

CREATE TABLE pedidos (
    id_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_cliente INTEGER NOT NULL,
    id_carrito INTEGER NOT NULL,
    estado_pedido VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    fecha_pedido TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pedidos_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_pedidos_carritos
        FOREIGN KEY (id_carrito) REFERENCES carritos (id_carrito),
    CONSTRAINT uk_pedidos_public_id UNIQUE (public_id),
    CONSTRAINT ck_pedidos_total_non_negative CHECK (total >= 0)
);

CREATE TABLE detalle_pedido (
    id_detalle_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_detalle_pedido_pedidos
        FOREIGN KEY (id_pedido) REFERENCES pedidos (id_pedido),
    CONSTRAINT fk_detalle_pedido_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT ck_detalle_pedido_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_pedido_precio_unitario_non_negative CHECK (precio_unitario >= 0),
    CONSTRAINT ck_detalle_pedido_subtotal_non_negative CHECK (subtotal >= 0)
);

CREATE TABLE ventas_pos (
    id_venta_pos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_trabajador INTEGER NOT NULL,
    id_cliente INTEGER,
    total NUMERIC(12, 2) NOT NULL DEFAULT 0,
    metodo_pago VARCHAR(40) NOT NULL,
    fecha_venta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ventas_pos_trabajadores
        FOREIGN KEY (id_trabajador) REFERENCES trabajadores (id_trabajador),
    CONSTRAINT fk_ventas_pos_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT uk_ventas_pos_public_id UNIQUE (public_id),
    CONSTRAINT ck_ventas_pos_total_non_negative CHECK (total >= 0)
);

CREATE TABLE detalle_venta_pos (
    id_detalle_venta_pos INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta_pos INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(12, 2) NOT NULL DEFAULT 0,
    CONSTRAINT fk_detalle_venta_pos_ventas_pos
        FOREIGN KEY (id_venta_pos) REFERENCES ventas_pos (id_venta_pos),
    CONSTRAINT fk_detalle_venta_pos_productos
        FOREIGN KEY (id_producto) REFERENCES productos (id_producto),
    CONSTRAINT ck_detalle_venta_pos_cantidad_positive CHECK (cantidad > 0),
    CONSTRAINT ck_detalle_venta_pos_precio_unitario_non_negative CHECK (precio_unitario >= 0),
    CONSTRAINT ck_detalle_venta_pos_subtotal_non_negative CHECK (subtotal >= 0)
);

CREATE TABLE pagos (
    id_pago INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_pedido INTEGER,
    id_venta_pos INTEGER,
    metodo_pago VARCHAR(40) NOT NULL,
    monto NUMERIC(12, 2) NOT NULL DEFAULT 0,
    estado_pago VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_pago TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pagos_pedidos
        FOREIGN KEY (id_pedido) REFERENCES pedidos (id_pedido),
    CONSTRAINT fk_pagos_ventas_pos
        FOREIGN KEY (id_venta_pos) REFERENCES ventas_pos (id_venta_pos),
    CONSTRAINT uk_pagos_public_id UNIQUE (public_id),
    CONSTRAINT ck_pagos_monto_non_negative CHECK (monto >= 0),
    CONSTRAINT ck_pagos_origen_exclusivo CHECK (
        (id_pedido IS NOT NULL AND id_venta_pos IS NULL)
        OR (id_pedido IS NULL AND id_venta_pos IS NOT NULL)
    )
);

CREATE TABLE consultas_chatbot (
    id_consulta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL DEFAULT gen_random_uuid(),
    id_cliente INTEGER NOT NULL,
    id_carrito INTEGER NOT NULL,
    pregunta TEXT NOT NULL,
    respuesta TEXT NOT NULL,
    fecha_consulta TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consultas_chatbot_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes (id_cliente),
    CONSTRAINT fk_consultas_chatbot_carritos
        FOREIGN KEY (id_carrito) REFERENCES carritos (id_carrito),
    CONSTRAINT uk_consultas_chatbot_public_id UNIQUE (public_id)
);

CREATE INDEX idx_rol_permiso_id_rol ON rol_permiso (id_rol);
CREATE INDEX idx_rol_permiso_id_permiso ON rol_permiso (id_permiso);
CREATE INDEX idx_usuarios_id_rol ON usuarios (id_rol);
CREATE INDEX idx_productos_id_categoria ON productos (id_categoria);
CREATE INDEX idx_productos_estado ON productos (estado);
CREATE INDEX idx_movimientos_inventario_id_producto ON movimientos_inventario (id_producto);
CREATE INDEX idx_movimientos_inventario_id_usuario ON movimientos_inventario (id_usuario);
CREATE INDEX idx_carritos_id_cliente ON carritos (id_cliente);
CREATE INDEX idx_detalle_carrito_id_carrito ON detalle_carrito (id_carrito);
CREATE INDEX idx_detalle_carrito_id_producto ON detalle_carrito (id_producto);
CREATE INDEX idx_pedidos_id_cliente ON pedidos (id_cliente);
CREATE INDEX idx_pedidos_id_carrito ON pedidos (id_carrito);
CREATE INDEX idx_pedidos_estado_pedido ON pedidos (estado_pedido);
CREATE INDEX idx_detalle_pedido_id_pedido ON detalle_pedido (id_pedido);
CREATE INDEX idx_detalle_pedido_id_producto ON detalle_pedido (id_producto);
CREATE INDEX idx_ventas_pos_id_trabajador ON ventas_pos (id_trabajador);
CREATE INDEX idx_ventas_pos_id_cliente ON ventas_pos (id_cliente);
CREATE INDEX idx_detalle_venta_pos_id_venta_pos ON detalle_venta_pos (id_venta_pos);
CREATE INDEX idx_detalle_venta_pos_id_producto ON detalle_venta_pos (id_producto);
CREATE INDEX idx_pagos_id_pedido ON pagos (id_pedido);
CREATE INDEX idx_pagos_id_venta_pos ON pagos (id_venta_pos);
CREATE INDEX idx_pagos_estado_pago ON pagos (estado_pago);
CREATE INDEX idx_consultas_chatbot_id_cliente ON consultas_chatbot (id_cliente);
CREATE INDEX idx_consultas_chatbot_id_carrito ON consultas_chatbot (id_carrito);
