CREATE TABLE codigos_recuperacion_contrasena (
    id_codigo_recuperacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    codigo_hash VARCHAR(255) NOT NULL,
    estado VARCHAR(30) NOT NULL DEFAULT 'PENDIENTE',
    fecha_creacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_expiracion TIMESTAMP NOT NULL,
    fecha_uso TIMESTAMP,
    CONSTRAINT fk_codigos_recuperacion_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios (id_usuario),
    CONSTRAINT chk_codigos_recuperacion_estado
        CHECK (estado IN ('PENDIENTE', 'UTILIZADO', 'EXPIRADO'))
);

CREATE INDEX idx_codigos_recuperacion_usuario_estado
    ON codigos_recuperacion_contrasena (id_usuario, estado, fecha_creacion DESC);
