CREATE TABLE seguimiento_pedidos (
    id_seguimiento_pedido INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido INTEGER NOT NULL,
    codigo_estado VARCHAR(50) NOT NULL,
    titulo VARCHAR(120) NOT NULL,
    descripcion TEXT,
    ubicacion VARCHAR(180),
    fecha_evento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_seguimiento_pedidos_pedidos
        FOREIGN KEY (id_pedido) REFERENCES pedidos (id_pedido)
);

CREATE INDEX idx_seguimiento_pedidos_pedido_fecha
    ON seguimiento_pedidos (id_pedido, fecha_evento DESC);

INSERT INTO seguimiento_pedidos (
    id_pedido, codigo_estado, titulo, descripcion, fecha_evento
)
SELECT p.id_pedido, ep.codigo, ep.nombre, ep.descripcion, p.fecha_pedido
FROM pedidos p
JOIN estados_pedido ep ON ep.id_estado_pedido = p.id_estado_pedido;
